import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Comment from "./Comment";
import { useState, useEffect , useRef } from "react";
import CommentData from "./db.json";
export default function Home() {
    const [box, setBox] = useState(false);
    const [parentId, setParentId] = useState();
    const [data, setData] = useState();

    const inputVal = useRef("")
    
    useEffect(()=>{
        setData(CommentData)
    },[CommentData])

    const openbox = (pid) => {
        setBox(true);
        setParentId(pid) ; 
    };


    const getParentComments = () => {
        return data?.filter((item) => item.parent_id === null);
    };
    const saveComment = () =>{
        console.log("input value is here"  , inputVal.current.value) ;
        console.log("The parent id is"  , parentId) ;
        let postData = [...data] ; 

        postData.push({
            id: Math.random() , 
            parent_id: parentId , 
            comment: inputVal.current.value
        })
        setData(postData) ; 
        setBox(false) ; 
        inputVal.current.value = "" ;
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            {getParentComments()?.map((item) => (
                <Comment id={item.id} content={item.comment} comments={data} openbox={openbox}></Comment>
            ))}
            {/* <div>
            <Comment content={"This is test1"} openbox={openbox}>
                <Comment openbox={openbox} content={"Okay If you say so"}></Comment>
                <Comment openbox={openbox} content={"Okay If you say so"}></Comment>
            </Comment>
            <Comment content={"This is new"} openbox={openbox} />
            </div> */}
            {box && (
                <div>
                    <input ref={inputVal} placeholder={"Enter comment here"} />
                    <button onClick={saveComment}>Save Comment</button>
                </div>
            )}
        </div>
    );
}
